### ISSUE TITLE
Runtimeerror during training

### ISSUE THREAD

**Issue by YangJae96** [caposerenity/DAPS#2]
Hi, I am facing some error while running your codes.

There was some error preparing the setting 
such as faiss-gpu, apex, ex..
but I made the code running and like below.
![image](https://user-images.githubusercontent.com/57695621/182163154-bd9cfe4b-e3e0-4433-9823-ad77cff4d7b3.png)

THe memory seems to be initalized but the error comes up right at the 
begin of training.
![image](https://user-images.githubusercontent.com/57695621/182162489-895b56ea-3c6a-44b6-88df-6529c0e54360.png)

Could you give some help?

**Comment by caposerenity** [comment]
Hi, @YangJae96 , it seems that Apex is not properly installed on your machine, you can try to re-install it. There won't be errors during memory initialization because apex amp is not employed in that process.

**Comment by YangJae96** [comment]
@caposerenity 
I am getting error when the code goes in through
proposals_s, proposal_losses_s = self.rpn(images_s, features_s, targets_s)

![image](https://user-images.githubusercontent.com/57695621/182171278-63565911-77e2-4fdb-9e38-1aff63c1b9d3.png)

Do you think the values that are inputed to self.rpn are not properly calculated because apex is not installed properly?

**Comment by YangJae96** [comment]
I see. I am runnning the training but it is taking a while.
Did it take more than a day to train the model in both setting?

**Comment by YangJae96** [comment]
Also, setting the PRW as source and CUHK as target  takes 
14GB memory when batch size is 2, 
and the reverse takes 14GB memory when batch size is 4.

Why is there so much memory difference in both settings? 

Maybe hybrid memory?

**Comment by caposerenity** [comment]
Hi, @YangJae96 , it takes about 30hours to train the model with PRW as the target domain on a single A100 GPUI. The reverse setting takes much less time because it achieves the best performance at the 7th epoch, you can get more training details from our provided train_log in README.

**Comment by YangJae96** [comment]
@caposerenity  Okay! Thank you for your detail explanation
