### ISSUE TITLE
About len_iter

### ISSUE THREAD

**Issue by Changryeol-Jeon** [caposerenity/DAPS#4]
https://github.com/caposerenity/DAPS/blob/a77577eddbcf983b494636279d317ce5aac50962/utils/utils.py#L84-L91

In that part of the code, CUHK-SYSU specifies len_itr as 2240, but the train_log you uploaded shows 1420. Why is there such a difference?

**Comment by caposerenity** [comment]
Thank you for your concern, you may find in line 87 in engine.py that the training iter is not determined by the setting in utils.py. You can refer to this issue for more information https://github.com/caposerenity/DAPS/issues/1

**Comment by Changryeol-Jeon** [comment]
Thank you for your great work and detailed explanation.
